;; ---------------------------------------------------------------------------
;;
;;  Modbus
;;
;;  Copyright © 2006,7  Peter Heinrich
;;  All Rights Reserved
;;
;;  $URL$
;;  $Revision$
;;
;; ---------------------------------------------------------------------------
;;  $Author$
;;  $Date$
;; ---------------------------------------------------------------------------



   processor 18f252
   radix dec
   list b=3

   #include <p18f252.inc>
   #include "../framework/macros.inc"
   #include "../framework/framework.inc"
   #include "modbus.inc"
